/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasTarefasRouteImport } from './routes/minhas-tarefas'
import { Route as IndexRouteImport } from './routes/index'

const MinhasTarefasRoute = MinhasTarefasRouteImport.update({
  id: '/minhas-tarefas',
  path: '/minhas-tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minhas-tarefas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minhas-tarefas'
  id: '__root__' | '/' | '/minhas-tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinhasTarefasRoute: typeof MinhasTarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas-tarefas': {
      id: '/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof MinhasTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinhasTarefasRoute: MinhasTarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
