/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MinhasTarefasRouteImport } from './routes/minhas-tarefas'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalasIndexRouteImport } from './routes/salas.index'
import { Route as SalasRoomNameRouteImport } from './routes/salas.$roomName'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasTarefasRoute = MinhasTarefasRouteImport.update({
  id: '/minhas-tarefas',
  path: '/minhas-tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasIndexRoute = SalasIndexRouteImport.update({
  id: '/salas/',
  path: '/salas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasRoomNameRoute = SalasRoomNameRouteImport.update({
  id: '/salas/$roomName',
  path: '/salas/$roomName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
  '/relatorios': typeof RelatoriosRoute
  '/salas/$roomName': typeof SalasRoomNameRoute
  '/salas/': typeof SalasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
  '/relatorios': typeof RelatoriosRoute
  '/salas/$roomName': typeof SalasRoomNameRoute
  '/salas': typeof SalasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/minhas-tarefas': typeof MinhasTarefasRoute
  '/relatorios': typeof RelatoriosRoute
  '/salas/$roomName': typeof SalasRoomNameRoute
  '/salas/': typeof SalasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/metas'
    | '/minhas-tarefas'
    | '/relatorios'
    | '/salas/$roomName'
    | '/salas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/metas'
    | '/minhas-tarefas'
    | '/relatorios'
    | '/salas/$roomName'
    | '/salas'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/metas'
    | '/minhas-tarefas'
    | '/relatorios'
    | '/salas/$roomName'
    | '/salas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EquipeRoute: typeof EquipeRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  MinhasTarefasRoute: typeof MinhasTarefasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SalasRoomNameRoute: typeof SalasRoomNameRoute
  SalasIndexRoute: typeof SalasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-tarefas': {
      id: '/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof MinhasTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas/': {
      id: '/salas/'
      path: '/salas'
      fullPath: '/salas/'
      preLoaderRoute: typeof SalasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas/$roomName': {
      id: '/salas/$roomName'
      path: '/salas/$roomName'
      fullPath: '/salas/$roomName'
      preLoaderRoute: typeof SalasRoomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EquipeRoute: EquipeRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  MinhasTarefasRoute: MinhasTarefasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SalasRoomNameRoute: SalasRoomNameRoute,
  SalasIndexRoute: SalasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
